"""
Django settings for globalstrat project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env (gitignored) into os.environ, if present, so secrets like
# DASHSCOPE_API_KEY survive process restarts without a systemd unit. Existing
# environment variables always win (does not override a real env). Best-effort.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env', override=False)
except Exception:
    pass

# ---------------------------------------------------------------------------
# Environment toggle: set GLOBALSTRAT_ENV=production in systemd / .env
# ---------------------------------------------------------------------------
ENVIRONMENT = os.environ.get('GLOBALSTRAT_ENV', 'development')
IS_PRODUCTION = ENVIRONMENT == 'production'
GIT_REVISION = os.environ.get('GIT_REVISION', '')
COMPETITION_BACKUP_DIR = Path(os.environ.get(
    'COMPETITION_BACKUP_DIR', BASE_DIR / 'competition_backups'))
COMPETITION_BACKUP_RETENTION_DAYS = int(os.environ.get(
    'COMPETITION_BACKUP_RETENTION_DAYS', '30'))
COMPETITION_BACKUP_PRUNE_ENABLED = (
    os.environ.get('COMPETITION_BACKUP_PRUNE_ENABLED', '').lower() == 'true')

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_SECRET_KEY = 'django-insecure-9*703tq1!eqol9@=4k4v_179%p74zhk@0q5@kz6am$6tu+4ib&'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

# Fail *closed* in production (W7). A deploy that forgets to set real secrets must
# REFUSE TO BOOT rather than silently sign JWTs with the committed
# django-insecure key (an auth-bypass risk, since JWT_SECRET_KEY = SECRET_KEY) or
# connect with the default DB password. Env-overridable everywhere else.
if IS_PRODUCTION:
    _insecure_secrets = []
    if os.environ.get('DJANGO_SECRET_KEY') is None or SECRET_KEY == _INSECURE_SECRET_KEY:
        _insecure_secrets.append('DJANGO_SECRET_KEY')
    if not os.environ.get('DB_PASSWORD'):
        _insecure_secrets.append('DB_PASSWORD')
    if _insecure_secrets:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'GLOBALSTRAT_ENV=production but these secrets are unset or still at '
            'their insecure committed defaults: ' + ', '.join(_insecure_secrets) +
            '. Set them in the environment before starting in production.'
        )

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.50.5',
    'globalstrat.camdani.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SessionHeartbeatMiddleware',
    'core.middleware.GamePauseGuardMiddleware',
    'core.middleware.TeamScopeGuardMiddleware',
    'core.middleware.SensitiveReadLogMiddleware',
]

ROOT_URLCONF = 'globalstrat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'globalstrat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'globalstrat_plus'),
        'USER': os.environ.get('DB_USER', 'donwh'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '***REMOVED-CREDENTIAL-V2-048***'),
        'HOST': os.environ.get('DB_HOST', '192.168.50.38'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'en-us')

# UTC everywhere by default. Django assigns os.environ['TZ'] from this value
# and calls tzset(), so it is the *process* timezone, not just a display
# preference — which is exactly why it is overridable: a determinism replay
# has to be able to run the resolution process under a genuinely different
# zone and show the competitive hash does not move.
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# CORS — tighten in production, allow all in development
# ---------------------------------------------------------------------------
if IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        'https://globalstrat.camdani.com',
    ]
else:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-user-id',
    'x-instance-id',
]

# ---------------------------------------------------------------------------
# CSRF & Security — production only
# ---------------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    'https://globalstrat.camdani.com',
]

if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = False   # Cloudflare handles SSL termination
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ---------------------------------------------------------------------------
# Logging — structured for production, verbose for development
# ---------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
    },
}

# RAG Configuration (CC-7)
QDRANT_HOST = os.environ.get('QDRANT_HOST', '192.168.50.186')
QDRANT_PORT = int(os.environ.get('QDRANT_PORT', 6333))
QDRANT_COLLECTION = os.environ.get('QDRANT_COLLECTION', 'globalstrat_plus_articles')

# Embedding model
EMBEDDING_MODEL = os.environ.get('EMBEDDING_MODEL', '/home/ubuntu/models/all-MiniLM-L6-v2')
EMBEDDING_DIMENSION = 384  # all-MiniLM-L6-v2 dimension

# DashScope (for LLM calls — brief generation, coherence evaluation)
DASHSCOPE_API_KEY = os.environ.get('DASHSCOPE_API_KEY', '')
DASHSCOPE_MODEL = os.environ.get('DASHSCOPE_MODEL', 'qwen3-max-preview')
DASHSCOPE_BASE_URL = 'https://dashscope-intl.aliyuncs.com/api/v1'
DASHSCOPE_COMPATIBLE_URL = os.environ.get('DASHSCOPE_COMPATIBLE_URL',
    'https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions')

# Set DashScope SDK base URL globally at import time
try:
    import dashscope as _dashscope
    _dashscope.base_http_api_url = DASHSCOPE_BASE_URL
except ImportError:
    pass

# Legacy compatibility flag. Resolution is now unconditionally fail-closed;
# this value remains temporarily for older integrations that import it.
SC_ENGINE_STRICT = os.environ.get(
    'SC_ENGINE_STRICT', 'true',
).lower() in ('1', 'true', 'yes')

# Full database recovery must only run while the application is in maintenance
# mode. The guarded management command refuses to execute unless enabled.
COMPETITION_RECOVERY_ENABLED = os.environ.get(
    'COMPETITION_RECOVERY_ENABLED', 'false',
).lower() in ('1', 'true', 'yes')

# RETIRED (V2-015 / V2-016). This used to blend the Phase-2 retrieval score
# into the stored coherence score — a field inside the competitive hash that
# services/grading.py also reads, so a student's mark depended on whether an
# external service answered. The path is removed, not merely defaulted off:
# a setting that a supported configuration can flip back is not a safe
# competition configuration.
#
# The name is kept only so that a stack still setting it fails loudly rather
# than believing retrieval is being graded when it is not — see
# core.services.narrative_jobs.require_safe_rag_configuration.
COMPETITION_RAG_AFFECTS_COHERENCE = os.environ.get(
    'COMPETITION_RAG_AFFECTS_COHERENCE', 'false',
).lower() in ('1', 'true', 'yes')

# A round scored from an uncommitted working tree cannot be reconstructed: the
# commit hash names the commit, not the modifications sitting on top of it.
# Resolution refuses such a build when this is on (the default in production).
COMPETITION_REQUIRE_CLEAN_BUILD = os.environ.get(
    'COMPETITION_REQUIRE_CLEAN_BUILD', 'true' if IS_PRODUCTION else 'false',
).lower() in ('1', 'true', 'yes')

# JWT Configuration (custom User model — uses PyJWT, not simplejwt)
JWT_SECRET_KEY = SECRET_KEY  # In production, use a dedicated key
JWT_ALGORITHM = 'HS256'
JWT_ACCESS_TOKEN_LIFETIME_HOURS = 8  # Long enough for a class session

# DRF: Use our custom JWT authentication.
# Default permission is AllowAny — endpoints that need auth use explicit permission_classes.
TEST_RUNNER = 'globalstrat.test_runner.GlobalStratTestRunner'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.JWTAuthentication',
    ],
    # Default to requiring a login. This was AllowAny, and 86 of 168 view
    # classes declared no permission_classes of their own, so they inherited it
    # — a team's strategic briefing, round status and financial reports were
    # readable by anyone on the internet with no credentials at all. Endpoints
    # that are genuinely public (login) now say so explicitly.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'decision_write': os.environ.get('DECISION_WRITE_RATE', '120/min'),
    },
}
