"""
Django settings for globalstrat project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Environment toggle: set GLOBALSTRAT_ENV=production in systemd / .env
# ---------------------------------------------------------------------------
ENVIRONMENT = os.environ.get('GLOBALSTRAT_ENV', 'development')
IS_PRODUCTION = ENVIRONMENT == 'production'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-9*703tq1!eqol9@=4k4v_179%p74zhk@0q5@kz6am$6tu+4ib&',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.50.5',
    'globalstrat.camdani.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'globalstrat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'globalstrat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'globalstrat_plus'),
        'USER': os.environ.get('DB_USER', 'donwh'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'donwhhostingroot'),
        'HOST': os.environ.get('DB_HOST', '192.168.50.38'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# CORS — tighten in production, allow all in development
# ---------------------------------------------------------------------------
if IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        'https://globalstrat.camdani.com',
    ]
else:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-user-id',
    'x-instance-id',
]

# ---------------------------------------------------------------------------
# CSRF & Security — production only
# ---------------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    'https://globalstrat.camdani.com',
]

if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = False   # Cloudflare handles SSL termination
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ---------------------------------------------------------------------------
# Logging — structured for production, verbose for development
# ---------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
    },
}

# RAG Configuration (CC-7)
QDRANT_HOST = os.environ.get('QDRANT_HOST', '192.168.50.186')
QDRANT_PORT = int(os.environ.get('QDRANT_PORT', 6333))
QDRANT_COLLECTION = os.environ.get('QDRANT_COLLECTION', 'globalstrat_articles')

# Embedding model
EMBEDDING_MODEL = os.environ.get('EMBEDDING_MODEL', '/home/ubuntu/models/all-MiniLM-L6-v2')
EMBEDDING_DIMENSION = 384  # all-MiniLM-L6-v2 dimension

# DashScope (for LLM calls — brief generation, coherence evaluation)
DASHSCOPE_API_KEY = os.environ.get('DASHSCOPE_API_KEY', '')
DASHSCOPE_MODEL = os.environ.get('DASHSCOPE_MODEL', 'qwen3-max-preview')
DASHSCOPE_BASE_URL = 'https://dashscope-intl.aliyuncs.com/api/v1'
DASHSCOPE_COMPATIBLE_URL = os.environ.get('DASHSCOPE_COMPATIBLE_URL',
    'https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions')

# Set DashScope SDK base URL globally at import time
try:
    import dashscope as _dashscope
    _dashscope.base_http_api_url = DASHSCOPE_BASE_URL
except ImportError:
    pass

# JWT Configuration (custom User model — uses PyJWT, not simplejwt)
JWT_SECRET_KEY = SECRET_KEY  # In production, use a dedicated key
JWT_ALGORITHM = 'HS256'
JWT_ACCESS_TOKEN_LIFETIME_HOURS = 8  # Long enough for a class session

# DRF: Use our custom JWT authentication.
# Default permission is AllowAny — endpoints that need auth use explicit permission_classes.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}
