# Generated by Django 5.2.4 on 2026-03-20 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_state_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('team_notes', models.TextField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_submissions', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_submissions', to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_submissions', to='core.team')),
            ],
            options={
                'db_table': 'decision_submission',
                'unique_together': {('team', 'round')},
            },
        ),
        migrations.CreateModel(
            name='DecisionResearchAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allocation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_allocations', to='core.marketdefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_allocations', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_research_allocation',
            },
        ),
        migrations.CreateModel(
            name='DecisionRDInvestment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('in_house', 'In-House'), ('license', 'License')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rd_investments', to='core.featuredefinition')),
                ('team_platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rd_investments', to='core.teamplatform')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_investments', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_rd_investment',
            },
        ),
        migrations.CreateModel(
            name='DecisionProductRetire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timing', models.CharField(choices=[('immediate', 'Immediate'), ('end_of_round', 'End of Round')], max_length=20)),
                ('team_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retire_decisions', to='core.teamproduct')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_retires', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_product_retire',
            },
        ),
        migrations.CreateModel(
            name='DecisionProductCreate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('positioning', models.CharField(choices=[('budget', 'Budget'), ('mainstream', 'Mainstream'), ('premium', 'Premium'), ('ultra_premium', 'Ultra-Premium')], max_length=20)),
                ('target_market_ids', models.JSONField()),
                ('team_platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_create_decisions', to='core.teamplatform')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creates', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_product_create',
            },
        ),
        migrations.CreateModel(
            name='DecisionPlatformDevelopment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('in_house', 'In-House'), ('license', 'License'), ('partnership', 'Partnership')], max_length=20)),
                ('committed_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('platform_generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_decisions', to='core.platformgenerationdefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_developments', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_platform_development',
            },
        ),
        migrations.CreateModel(
            name='DecisionPlant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('build', 'Build'), ('expand', 'Expand'), ('contract_mfg', 'Contract Manufacturing')], max_length=20)),
                ('capacity_units', models.IntegerField(blank=True, null=True)),
                ('contract_mfg_volume', models.IntegerField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_decisions', to='core.marketdefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_decisions', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_plant',
            },
        ),
        migrations.CreateModel(
            name='DecisionPartnership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('annual_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('action', models.CharField(choices=[('establish', 'Establish'), ('modify', 'Modify'), ('terminate', 'Terminate')], max_length=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnership_decisions', to='core.marketdefinition')),
                ('strategy_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnership_decisions', to='core.strategyoptiondefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_partnership',
            },
        ),
        migrations.CreateModel(
            name='DecisionMarketEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('action', models.CharField(choices=[('enter', 'Enter'), ('change_mode', 'Change Mode'), ('exit', 'Exit')], max_length=20)),
                ('entry_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_decisions', to='core.entrymodedefinition')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_decisions', to='core.marketdefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_entries', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_market_entry',
            },
        ),
        migrations.CreateModel(
            name='DecisionFinancing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debt_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dividend_per_share', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financing', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_financing',
            },
        ),
        migrations.CreateModel(
            name='DecisionEventResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_instance_id', models.IntegerField(blank=True, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_responses', to='core.eventresponsedefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_responses', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_event_response',
            },
        ),
        migrations.CreateModel(
            name='DecisionESG',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('environmental_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('social_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('governance_commitments', models.JSONField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esg', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_esg',
            },
        ),
        migrations.CreateModel(
            name='DecisionBudgetAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rd_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marketing_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('strategy_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('research_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocation', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_budget_allocation',
            },
        ),
        migrations.CreateModel(
            name='DecisionAcquisition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisition_decisions', to='core.marketdefinition')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acquisition_decisions', to='core.aicompetitordefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_acquisition',
            },
        ),
        migrations.CreateModel(
            name='DecisionMarketing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('promotion_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('campaign_focus_feature_ids', models.JSONField()),
                ('channel_digital_pct', models.DecimalField(decimal_places=4, max_digits=5)),
                ('channel_traditional_pct', models.DecimalField(decimal_places=4, max_digits=5)),
                ('channel_trade_pct', models.DecimalField(decimal_places=4, max_digits=5)),
                ('distribution_strategy', models.CharField(choices=[('mass_retail', 'Mass Retail'), ('selective_retail', 'Selective Retail'), ('exclusive_retail', 'Exclusive Retail'), ('direct_online', 'Direct Online'), ('hybrid', 'Hybrid')], max_length=30)),
                ('distribution_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('production_volume', models.IntegerField()),
                ('demand_estimate', models.IntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_decisions', to='core.marketdefinition')),
                ('production_source_market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_source_decisions', to='core.marketdefinition')),
                ('team_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_decisions', to='core.teamproduct')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_decisions', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_marketing',
                'unique_together': {('submission', 'team_product', 'market')},
            },
        ),
    ]
