# Generated by Django 5.2.4 on 2026-03-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cc06_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQueryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('source_tags_used', models.CharField(blank=True, max_length=500, null=True)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_queries', to='core.team')),
            ],
            options={
                'db_table': 'research_query_log',
            },
        ),
    ]
