# Generated by Django 5.2.4 on 2026-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_researchquerylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='shareholder_return',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roundresultfinancials',
            name='debt_to_equity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roundresultfinancials',
            name='gross_margin_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roundresultfinancials',
            name='net_margin_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roundresultfinancials',
            name='roe',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roundresultfinancials',
            name='shareholder_return_cumulative',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
