# Generated by Django 5.2.4 on 2026-03-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_widen_ratio_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(default=dict)),
                ('projected_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_scenarios', to='core.team')),
            ],
            options={
                'db_table': 'forecast_scenario',
            },
        ),
        migrations.CreateModel(
            name='TeamFrameworkAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('framework_type', models.CharField(choices=[('porter', "Porter's Five Forces"), ('pestle', 'PESTLE Analysis'), ('swot', 'SWOT Analysis'), ('entry_matrix', 'Market Entry Decision Matrix'), ('ansoff', 'Ansoff Growth Matrix')], max_length=50)),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='framework_analyses', to='core.marketdefinition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_analyses', to='core.team')),
            ],
            options={
                'db_table': 'team_framework_analysis',
            },
        ),
    ]
