# Generated by Django 5.2.4 on 2026-03-21 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_forecastscenario_teamframeworkanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionmarketing',
            name='sales_team_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionrdinvestment',
            name='calculated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='decisionrdinvestment',
            name='target_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decisionrdinvestment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='FeatureLevelCost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('cumulative_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('incremental_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_costs', to='core.featuredefinition')),
                ('platform_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_level_costs', to='core.platformgenerationdefinition')),
            ],
            options={
                'db_table': 'feature_level_cost',
                'ordering': ['feature', 'platform_generation', 'level'],
                'unique_together': {('feature', 'platform_generation', 'level')},
            },
        ),
    ]
