# Generated by Django 5.2.4 on 2026-03-21 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_decisionmarketing_sales_team_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTalent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rd_headcount', models.IntegerField(default=50)),
                ('rd_salary_level', models.IntegerField(choices=[(1, 'Below Market ($60K/yr)'), (2, 'Market Rate ($90K/yr)'), (3, 'Above Market ($120K/yr)'), (4, 'Premium ($160K/yr)'), (5, 'Top of Market ($220K/yr)')], default=3)),
                ('rd_training_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commercial_headcount', models.IntegerField(default=30)),
                ('commercial_salary_level', models.IntegerField(choices=[(1, 'Below Market ($60K/yr)'), (2, 'Market Rate ($90K/yr)'), (3, 'Above Market ($120K/yr)'), (4, 'Premium ($160K/yr)'), (5, 'Top of Market ($220K/yr)')], default=3)),
                ('commercial_training_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operations_headcount', models.IntegerField(default=40)),
                ('operations_salary_level', models.IntegerField(choices=[(1, 'Below Market ($60K/yr)'), (2, 'Market Rate ($90K/yr)'), (3, 'Above Market ($120K/yr)'), (4, 'Premium ($160K/yr)'), (5, 'Top of Market ($220K/yr)')], default=3)),
                ('operations_training_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'decision_talent',
            },
        ),
        migrations.CreateModel(
            name='TeamTalentState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('talent_pool', models.CharField(choices=[('rd', 'R&D'), ('commercial', 'Commercial'), ('operations', 'Operations')], max_length=30)),
                ('headcount', models.IntegerField(default=0)),
                ('salary_level', models.IntegerField(default=3)),
                ('cumulative_training', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('talent_level', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('turnover_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5)),
                ('round_number', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_states', to='core.team')),
            ],
            options={
                'db_table': 'team_talent_state',
                'unique_together': {('team', 'talent_pool', 'round_number')},
            },
        ),
    ]
