# Generated by Django 5.2.4 on 2026-03-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_decisiontalent_teamtalentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionplatformdevelopment',
            name='feature_levels',
            field=models.JSONField(blank=True, default=dict, help_text='Dict mapping feature_id → target_level for the new platform'),
        ),
        migrations.AddField(
            model_name='decisionplatformdevelopment',
            name='platform_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
