# Generated by Django 5.2.4 on 2026-03-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_platform_name_and_feature_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionmarketing',
            name='distribution_channel_detail',
            field=models.JSONField(blank=True, default=dict, help_text='Per-channel sales rep assignments, e.g. {"mass_retail": 3, "direct_online": 2}'),
        ),
    ]
