# Generated by Django 5.2.4 on 2026-03-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cc20_mna_esg_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicompetitorbehavior',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DecisionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('page', models.CharField(max_length=50)),
                ('change_description', models.CharField(max_length=500)),
                ('change_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.user')),
            ],
            options={
                'db_table': 'decision_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('alert_type', models.CharField(choices=[('strategic', 'Strategic Concern'), ('financial', 'Financial Warning'), ('missed_opportunity', 'Missed Opportunity'), ('notable_move', 'Notable Decision'), ('learning_moment', 'Teaching Opportunity'), ('distress', 'Team in Distress')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('watch', 'Watch'), ('concern', 'Concern'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('teaching_note', models.TextField(blank=True, default='')),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_alerts', to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_alerts', to='core.team')),
            ],
            options={
                'db_table': 'instructor_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
