# Generated by Django 5.2.4 on 2026-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cc21_instructor_alerts_change_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplatform',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Team-assigned platform name (falls back to generation name)', max_length=100),
        ),
    ]
