# Generated by Django 5.2.4 on 2026-03-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_team_platform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGEconomicImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('benefit_type', models.CharField(choices=[('tariff_reduction', 'Tariff Reduction'), ('tax_incentive', 'Tax Incentive'), ('cogs_reduction', 'COGS Reduction'), ('event_protection', 'Event Protection')], max_length=50)),
                ('base_value', models.DecimalField(decimal_places=2, default=0, help_text='What the cost would have been without ESG benefit', max_digits=15)),
                ('effective_value', models.DecimalField(decimal_places=2, default=0, help_text='What the cost actually was after ESG benefit', max_digits=15)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('esg_level', models.DecimalField(decimal_places=2, default=0, help_text='The esg_track_record level that triggered this benefit', max_digits=5)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_impacts', to='core.game')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esg_impacts', to='core.marketdefinition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_impacts', to='core.team')),
            ],
            options={
                'db_table': 'esg_economic_impact',
            },
        ),
        migrations.CreateModel(
            name='PartnershipEconomicImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('benefit_type', models.CharField(max_length=50)),
                ('benefit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_impacts', to='core.game')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_impacts', to='core.teampartnership')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_impacts', to='core.team')),
            ],
            options={
                'db_table': 'partnership_economic_impact',
            },
        ),
        migrations.CreateModel(
            name='TalentEconomicImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('rd_talent_level', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('rd_cost_modifier', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('rd_cost_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commercial_talent_level', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('campaign_effectiveness_modifier', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('campaign_revenue_uplift', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operations_talent_level', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('cogs_modifier', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('cogs_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_talent_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_talent_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_talent_roi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_impacts', to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_impacts', to='core.team')),
            ],
            options={
                'db_table': 'talent_economic_impact',
                'unique_together': {('game', 'team', 'round_number')},
            },
        ),
    ]
