# Generated by Django 5.2.4 on 2026-03-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cc24_strategic_economics'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredefinition',
            name='is_derived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='is_market_specific',
            field=models.BooleanField(default=False),
        ),
    ]
