# Generated by Django 5.2.4 on 2026-03-21 13:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cc25_derived_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='share_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='AIInvestorFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('investment_philosophy', models.CharField(choices=[('growth', 'Growth — chases revenue growth, R&D, expansion'), ('value', 'Value — wants low debt, strong margins, dividends'), ('esg', 'ESG — weights sustainability, governance, social impact')], max_length=30)),
                ('initial_holding_pct', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('max_holding_pct', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=5)),
                ('min_holding_pct', models.DecimalField(decimal_places=4, default=Decimal('0.02'), max_digits=5)),
                ('trade_aggressiveness', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Fraction of target change executed per round (0-1)', max_digits=3)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_funds', to='core.scenario')),
            ],
            options={
                'db_table': 'ai_investor_fund',
                'unique_together': {('scenario', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AIInvestorHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('shares_held', models.IntegerField()),
                ('holding_pct', models.DecimalField(decimal_places=4, max_digits=7)),
                ('satisfaction_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('action', models.CharField(choices=[('buy', 'Bought shares'), ('sell', 'Sold shares'), ('hold', 'Held position'), ('initial', 'Initial allocation')], max_length=10)),
                ('shares_traded', models.IntegerField(default=0)),
                ('trade_reason', models.CharField(blank=True, default='', max_length=500)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core.aiinvestorfund')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_holdings', to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_holdings', to='core.team')),
            ],
            options={
                'db_table': 'ai_investor_holding',
                'ordering': ['round_number', 'fund'],
                'unique_together': {('game', 'fund', 'team', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='AIInvestorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(max_length=50)),
                ('feature_label', models.CharField(max_length=200)),
                ('ideal_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tolerance', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.aiinvestorfund')),
            ],
            options={
                'db_table': 'ai_investor_preference',
                'unique_together': {('fund', 'feature_code')},
            },
        ),
        migrations.CreateModel(
            name='SharePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('book_value_per_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sentiment_multiplier', models.DecimalField(decimal_places=4, max_digits=5)),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_shares_outstanding', models.IntegerField()),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('velocity_satisfaction', models.DecimalField(decimal_places=4, max_digits=5)),
                ('granite_satisfaction', models.DecimalField(decimal_places=4, max_digits=5)),
                ('greenhorizon_satisfaction', models.DecimalField(decimal_places=4, max_digits=5)),
                ('aggregate_demand', models.DecimalField(decimal_places=4, max_digits=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_price_history', to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_price_history', to='core.team')),
            ],
            options={
                'db_table': 'share_price_history',
                'unique_together': {('game', 'team', 'round_number')},
            },
        ),
    ]
