# Generated by Django 5.2.4 on 2026-03-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cc26_capital_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundresultadoption',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adoption_results', to='core.marketdefinition'),
        ),
    ]
