# Generated by Django 5.2.4 on 2026-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_allow_null_market_on_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionbudgetallocation',
            name='research_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
