# Generated by Django 5.2.4 on 2026-03-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_research_budget_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('executive_summary', models.TextField()),
                ('performance_analysis', models.JSONField()),
                ('investment_returns', models.JSONField()),
                ('investor_sentiment', models.JSONField()),
                ('competitive_landscape', models.JSONField()),
                ('strategic_recommendations', models.JSONField()),
                ('risk_alerts', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_team', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_briefings', to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_briefings', to='core.team')),
            ],
            options={
                'db_table': 'strategic_briefing',
                'ordering': ['-round_number'],
                'unique_together': {('game', 'team', 'round_number')},
            },
        ),
    ]
