# Generated by Django 5.2.4 on 2026-03-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cc27_strategic_briefing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicbriefing',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='strategicbriefing',
            name='read_by_team',
        ),
        migrations.CreateModel(
            name='BriefingReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.strategicbriefing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_reads', to='core.user')),
            ],
            options={
                'db_table': 'briefing_read_status',
                'unique_together': {('briefing', 'user')},
            },
        ),
    ]
