# Generated by Django 5.2.4 on 2026-03-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cc27_per_user_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresultfinancials',
            name='gross_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='roundresultfinancials',
            name='total_channel_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='roundresultproductmarket',
            name='channel_margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='roundresultproductmarket',
            name='channel_margin_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='roundresultproductmarket',
            name='distribution_strategy',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='roundresultproductmarket',
            name='gross_local_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
