# Generated by Django 5.2.4 on 2026-03-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_channel_margin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionmarketentry',
            name='integration_strategy',
            field=models.CharField(blank=True, choices=[('FULL', 'Full Integration'), ('BRAND_PRESERVE', 'Brand Preservation'), ('DUAL_BRAND', 'Dual Brand')], default='FULL', help_text='Only applicable for acquisitions. Determines trust impact and operating cost.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roundresultfinancials',
            name='repatriation_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit lost to cross-border consolidation friction', max_digits=14),
        ),
        migrations.AddField(
            model_name='team',
            name='home_market',
            field=models.ForeignKey(blank=True, help_text="Team's country of origin. Affects trust, cultural distance, repatriation costs.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_teams', to='core.marketdefinition'),
        ),
        migrations.AddField(
            model_name='teammarketpresence',
            name='brand_preserved',
            field=models.BooleanField(default=False, help_text='True if acquired via Brand Preservation or Dual Brand strategy'),
        ),
        migrations.AddField(
            model_name='teammarketpresence',
            name='ip_exposure_cumulative',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative IP exposure from JV/licensing. 0.0 = none, increases per round.', max_digits=4),
        ),
        migrations.AddField(
            model_name='teamplatform',
            name='licensed_dependency_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Proportion of platform features developed via licensing (0.0-1.0). Higher = more vulnerable to technology sanctions.', max_digits=4),
        ),
        migrations.CreateModel(
            name='ComplianceInvestment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Dollar investment this round in compliance and localization for this market', max_digits=12)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketdefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_investments', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'compliance_investment',
                'unique_together': {('submission', 'market')},
            },
        ),
        migrations.CreateModel(
            name='CulturalDistanceMatrix',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance_level', models.CharField(choices=[('HOME', 'Home Market'), ('LOW', 'Low Distance'), ('MEDIUM', 'Medium Distance'), ('HIGH', 'High Distance'), ('VERY_HIGH', 'Very High Distance')], help_text='Cultural/institutional distance classification', max_length=20)),
                ('base_effectiveness', models.DecimalField(decimal_places=2, help_text='Base talent effectiveness multiplier before localization investment. 1.00 = home market.', max_digits=4)),
                ('repatriation_cost_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of profits lost during cross-border consolidation. 0 for home market.', max_digits=4)),
                ('from_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_from', to='core.marketdefinition')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_distances', to='core.scenario')),
                ('to_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_to', to='core.marketdefinition')),
            ],
            options={
                'db_table': 'cultural_distance_matrix',
                'unique_together': {('scenario', 'from_market', 'to_market')},
            },
        ),
        migrations.CreateModel(
            name='OriginTrustModifier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_trust_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier on customer fit scores. 1.0 = no penalty. Lower = more distrust.', max_digits=4)),
                ('regulator_origin_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Added to regulator satisfaction. Negative = scrutiny, positive = favorable.', max_digits=4)),
                ('trust_erosion_rate', models.DecimalField(decimal_places=2, default=0.02, help_text='Per-round improvement in trust multiplier from sustained presence and compliance.', max_digits=4)),
                ('host_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_as_host', to='core.marketdefinition')),
                ('origin_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_as_origin', to='core.marketdefinition')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_trust_modifiers', to='core.scenario')),
            ],
            options={
                'db_table': 'origin_trust_modifier',
                'unique_together': {('scenario', 'origin_market', 'host_market')},
            },
        ),
        migrations.CreateModel(
            name='TalentAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('talent_pool', models.CharField(choices=[('rd', 'R&D Team'), ('commercial', 'Sales & Marketing Team'), ('operations', 'Operations & Supply Chain Team')], max_length=30)),
                ('hq_count', models.IntegerField(default=0, help_text='Headcount stationed at headquarters')),
                ('market_allocation', models.JSONField(default=dict, help_text='Headcount per market code. Keys = market codes, values = integer headcount.')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_allocations', to='core.decisionsubmission')),
            ],
            options={
                'db_table': 'talent_allocation',
                'unique_together': {('submission', 'talent_pool')},
            },
        ),
        migrations.CreateModel(
            name='TeamMarketCompliance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cumulative_investment', models.DecimalField(decimal_places=2, default=0, help_text='Total compliance investment in this market across all rounds', max_digits=14)),
                ('compliance_level', models.DecimalField(decimal_places=2, default=0, help_text='0.0 = no compliance adaptation, 1.0 = fully localized', max_digits=4)),
                ('current_trust_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Current trust multiplier after accounting for sustained presence and compliance', max_digits=4)),
                ('effective_rd_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('effective_commercial_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('effective_operations_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('rounds_present', models.IntegerField(default=0, help_text='Consecutive rounds with active market presence')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketdefinition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'db_table': 'team_market_compliance',
                'unique_together': {('game', 'team', 'market')},
            },
        ),
    ]
