# Generated by Django 5.2.4 on 2026-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_decisionmarketentry_integration_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplatedefinition',
            name='affected_markets',
            field=models.JSONField(blank=True, default=None, help_text='List of market codes where this event can fire. Null = use target_market/affects_all_markets logic.', null=True),
        ),
        migrations.AddField(
            model_name='eventtemplatedefinition',
            name='target_type',
            field=models.CharField(choices=[('MARKET_WIDE', 'Affects all teams in the market'), ('TEAM_SPECIFIC', 'Targets specific teams based on conditions')], default='MARKET_WIDE', help_text='MARKET_WIDE fires once for the market. TEAM_SPECIFIC evaluates per-team.', max_length=20),
        ),
        migrations.AddField(
            model_name='eventtemplatedefinition',
            name='trigger_condition',
            field=models.JSONField(blank=True, default=None, help_text='JSON condition(s) evaluated per-team for TEAM_SPECIFIC events. Single dict or list of dicts (AND logic). Format: {attribute, operator, value}.', null=True),
        ),
    ]
