# Generated by Django 5.2.4 on 2026-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cc31e_event_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinvestorfund',
            name='profile',
            field=models.JSONField(blank=True, help_text='Fund strategy profile for student-facing display', null=True),
        ),
    ]
