# Generated by Django 5.2.4 on 2026-03-22 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_cc32a_communications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcommunication',
            name='evaluation',
            field=models.JSONField(blank=True, help_text='LLM evaluation results: overall_score, criteria_scores, strengths, gaps, etc.', null=True),
        ),
        migrations.CreateModel(
            name='OrganizationalStructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_overhead_per_round', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_market_coordination_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hq_talent_effectiveness_modifier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier on HQ talent contribution to global capability', max_digits=4)),
                ('local_talent_effectiveness_modifier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier on local market talent effectiveness', max_digits=4)),
                ('innovation_modifier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier on R&D output (feature level gains per investment)', max_digits=4)),
                ('coordination_efficiency', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier on cross-market campaign effectiveness and supply chain optimization', max_digits=4)),
                ('decision_speed_modifier', models.DecimalField(decimal_places=2, default=1.0, help_text='Affects market entry speed and plant construction time. >1.0 = faster.', max_digits=4)),
                ('optimal_market_range_min', models.IntegerField(default=1)),
                ('optimal_market_range_max', models.IntegerField(default=5)),
                ('overextension_cost_per_market', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overextension_effectiveness_penalty', models.DecimalField(decimal_places=2, default=0, help_text='Percentage reduction in all effectiveness modifiers per market beyond optimal range', max_digits=4)),
                ('transition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transition_disruption_rounds', models.IntegerField(default=0, help_text='Rounds of reduced effectiveness during transition. 0 = immediate.')),
                ('display_order', models.IntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_structures', to='core.scenario')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('scenario', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TeamOrganizationalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_round', models.IntegerField(default=0)),
                ('transition_rounds_remaining', models.IntegerField(default=0)),
                ('current_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_teams', to='core.organizationalstructuretype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('transitioning_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitioning_from', to='core.organizationalstructuretype')),
            ],
            options={
                'unique_together': {('game', 'team')},
            },
        ),
    ]
