# Generated by Django 5.2.4 on 2026-03-22 13:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cc32b_org_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlliancePartnerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('partnership_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('partner_type', models.CharField(choices=[('DISTRIBUTION', 'Distribution Partner'), ('TECHNOLOGY', 'Technology Partner'), ('GOVERNMENT', 'Government / Regulatory Advisor'), ('BRAND', 'Brand Ambassador'), ('LOCAL_STRATEGIC', 'Local Strategic Partner')], max_length=30)),
                ('description', models.TextField(help_text='Who this partner is and what they care about')),
                ('preferences', models.JSONField(help_text='List of {feature, weight, description} dicts evaluated each round')),
                ('satisfaction_floor', models.DecimalField(decimal_places=2, default=0.3, help_text='Below this level, partner initiates dissolution', max_digits=4)),
                ('renegotiation_threshold', models.DecimalField(decimal_places=2, default=0.5, help_text='Below this level, partner demands renegotiation', max_digits=4)),
                ('patience_rounds', models.IntegerField(default=2, help_text='Rounds of sustained dissatisfaction before partner acts')),
                ('benefit_curve', models.CharField(choices=[('LINEAR', 'Benefits scale linearly with satisfaction'), ('THRESHOLD', 'Full benefits above 0.7, degraded below'), ('BINARY', 'Full benefits above floor, zero below')], default='LINEAR', max_length=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_profiles', to='core.marketdefinition')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_profiles', to='core.scenario')),
            ],
            options={
                'db_table': 'alliance_partner_profile',
                'unique_together': {('scenario', 'partnership_code', 'market')},
            },
        ),
        migrations.CreateModel(
            name='TaxStructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('setup_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_maintenance_cost', models.DecimalField(decimal_places=2, default=0, help_text='Per-round cost for legal, accounting, and compliance', max_digits=10)),
                ('effective_tax_reduction_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage point reduction in effective tax rate across foreign markets', max_digits=4)),
                ('repatriation_cost_reduction_pct', models.DecimalField(decimal_places=2, default=0, help_text='Fraction reduction in repatriation costs (0.0 to 1.0)', max_digits=4)),
                ('audit_probability_per_round', models.DecimalField(decimal_places=2, default=0, help_text='Probability of a tax audit event per round', max_digits=4)),
                ('audit_penalty_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Multiplier on back-taxes + penalty if audited', max_digits=4)),
                ('value_investor_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Granite Investments satisfaction modifier', max_digits=4)),
                ('esg_investor_modifier', models.DecimalField(decimal_places=2, default=0, help_text='GreenHorizon satisfaction modifier', max_digits=4)),
                ('regulator_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Applied to regulator satisfaction in all markets', max_digits=4)),
                ('anti_corruption_conflict', models.BooleanField(default=False, help_text='If True, creates visible hypocrisy when combined with Anti-Corruption commitment')),
                ('display_order', models.IntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_structures', to='core.scenario')),
            ],
            options={
                'db_table': 'tax_structure_type',
                'ordering': ['display_order'],
                'unique_together': {('scenario', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TeamAllianceState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('satisfaction', models.DecimalField(decimal_places=2, default=0.7, max_digits=4)),
                ('feature_satisfaction', models.JSONField(default=dict)),
                ('rounds_below_renegotiation', models.IntegerField(default=0)),
                ('rounds_below_dissolution', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('HEALTHY', 'Operating normally'), ('STRAINED', 'Below renegotiation threshold — benefits degrading'), ('RENEGOTIATING', 'Partner demanding new terms'), ('DISSOLVING', 'Partnership ending — wind-down period'), ('DISSOLVED', 'Partnership terminated')], default='HEALTHY', max_length=20)),
                ('benefit_delivery_pct', models.DecimalField(decimal_places=2, default=1.0, help_text='0.0 to 1.0 — percentage of partnership benefits delivered', max_digits=4)),
                ('renegotiation_demands', models.JSONField(blank=True, null=True)),
                ('established_round', models.IntegerField(default=0)),
                ('dissolved_round', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_states', to='core.marketdefinition')),
                ('partner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_states', to='core.alliancepartnerprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'db_table': 'team_alliance_state',
                'unique_together': {('game', 'team', 'partner_profile')},
            },
        ),
        migrations.CreateModel(
            name='TeamTaxStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_round', models.IntegerField(default=0)),
                ('setup_cost_paid', models.BooleanField(default=False)),
                ('times_audited', models.IntegerField(default=0)),
                ('cumulative_audit_penalties', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cumulative_tax_savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_audit_round', models.IntegerField(blank=True, null=True)),
                ('current_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taxstructuretype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'db_table': 'team_tax_structure',
                'unique_together': {('game', 'team')},
            },
        ),
    ]
