# Generated by Django 5.2.4 on 2026-03-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_cc32d_alliance_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('convergence_iterations', models.IntegerField(default=0)),
                ('total_actions', models.IntegerField(default=0)),
                ('total_narratives', models.IntegerField(default=0)),
                ('agent_summary', models.JSONField(default=dict, help_text='Per-agent stats: {agent_class: {actions_proposed, actions_revised, actions_applied}}')),
                ('action_log', models.JSONField(blank=True, null=True)),
                ('narrative_items', models.JSONField(blank=True, null=True)),
                ('errors', models.JSONField(default=list)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_cycle_logs', to='core.game')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_cycle_logs', to='core.round')),
            ],
            options={
                'unique_together': {('game', 'round')},
            },
        ),
    ]
