# Generated by Django 5.2.4 on 2026-03-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_cc32e_agent_cycle_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('INCENTIVE_GRANT', 'Tax holiday, land grant, or permit expedition'), ('PROCUREMENT_AWARD', 'Government contract awarded'), ('TARIFF_ADJUSTMENT', 'Tariff rate change for specific origin'), ('REGULATORY_TIGHTENING', 'New compliance requirements'), ('REGULATORY_RELAXATION', 'Reduced requirements to attract investment'), ('BILATERAL_SHIFT', 'Trade policy change between two markets'), ('WARNING_ISSUED', 'Official warning to a firm'), ('ACCESS_RESTRICTION', 'Operating restrictions applied'), ('ACCESS_RESTORED', 'Restrictions lifted after improvement')], max_length=30)),
                ('parameters', models.JSONField(default=dict)),
                ('narrative', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketdefinition')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('target_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_policy', to='core.marketdefinition')),
                ('target_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'db_table': 'government_action',
            },
        ),
        migrations.CreateModel(
            name='GovernmentProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('policy_priorities', models.JSONField(help_text='List of {objective, weight, description} dicts. Objectives: local_employment, technology_transfer, tax_revenue, esg_compliance, local_manufacturing, export_contribution.')),
                ('incentive_threshold', models.DecimalField(decimal_places=2, default=0.7, help_text='Above this → eligible for incentives', max_digits=4)),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=0.4, help_text='Below this → government issues warning', max_digits=4)),
                ('restriction_threshold', models.DecimalField(decimal_places=2, default=0.25, help_text='Below this for patience_rounds → market access restrictions', max_digits=4)),
                ('max_incentive_value_per_round', models.DecimalField(decimal_places=2, default=2000000, help_text='Maximum incentive value per round across all firms', max_digits=12)),
                ('procurement_budget_per_round', models.DecimalField(decimal_places=2, default=3000000, help_text='Procurement contract value available each round', max_digits=12)),
                ('procurement_frequency', models.IntegerField(default=2, help_text='Procurement contract available every N rounds')),
                ('policy_volatility', models.DecimalField(decimal_places=2, default=0.1, help_text='Probability per round of a bilateral policy shift', max_digits=4)),
                ('patience_rounds', models.IntegerField(default=2)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_profile', to='core.marketdefinition')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_profiles', to='core.scenario')),
            ],
            options={
                'db_table': 'government_profile',
                'unique_together': {('scenario', 'market')},
            },
        ),
        migrations.CreateModel(
            name='GovernmentSatisfaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('satisfaction', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('objective_scores', models.JSONField(default=dict)),
                ('rounds_below_warning', models.IntegerField(default=0)),
                ('rounds_below_restriction', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('WELCOMED', 'Government actively supports this firm'), ('NEUTRAL', 'Standard operating conditions'), ('MONITORED', 'Government watching closely'), ('WARNING', 'Official warning issued'), ('RESTRICTED', 'Operating restrictions applied')], default='NEUTRAL', max_length=20)),
                ('active_incentive', models.JSONField(blank=True, null=True)),
                ('active_restriction', models.JSONField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketdefinition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'db_table': 'government_satisfaction',
                'unique_together': {('game', 'team', 'market')},
            },
        ),
    ]
