# Generated by Django 5.2.4 on 2026-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_cc32f_government_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='narrative_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='round',
            name='narrative_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='phase_1_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='phase_2_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Not yet processed'), ('PROCESSING', 'Phase 1 in progress'), ('RESULTS_AVAILABLE', 'Numbers ready, narratives pending'), ('FULLY_COMPLETE', 'All content generated'), ('FAILED', 'Processing failed')], default='PENDING', max_length=20),
        ),
    ]
