# Generated by Django 5.2.4 on 2026-03-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cc32h_round_processing_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firmstarterplatformconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='firmstarterplatformconfig',
            name='platform_label',
            field=models.CharField(default='alpha', max_length=20),
        ),
        migrations.AddField(
            model_name='firmstarterproduct',
            name='platform_label',
            field=models.CharField(default='alpha', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='firmstarterplatformconfig',
            unique_together={('firm_starter_profile', 'platform_label', 'feature')},
        ),
    ]
