# Generated by Django 5.2.4 on 2026-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_archived_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitiontarget',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='acquisitiontarget',
            name='target_name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aicompetitordefinition',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aicompetitordefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aiinvestorfund',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiinvestorfund',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alliancepartnerprofile',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alliancepartnerprofile',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='communicationassignment',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='communicationassignment',
            name='prompt_text_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entrymodedefinition',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entrymodedefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventresponsedefinition',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventresponsedefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventtemplatedefinition',
            name='description_template_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventtemplatedefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='featuredefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='firmstarterprofile',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='firmstarterprofile',
            name='profile_name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='governancecommitmenttype',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='governancecommitmenttype',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='governmentprofile',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='governmentprofile',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='marketdefinition',
            name='display_name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='marketdefinition',
            name='market_description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketdefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='organizationalstructuretype',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organizationalstructuretype',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='platformgenerationdefinition',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformgenerationdefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='segmentdefinition',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='segmentdefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='strategyoptiondefinition',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategyoptiondefinition',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='taxstructuretype',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taxstructuretype',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
