# Generated by Django 5.2.4 on 2026-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_acquisitiontarget_description_zh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='num_rounds',
            field=models.IntegerField(default=10),
        ),
    ]
