# Generated by Django 5.2.4 on 2026-04-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_cc35_promote_teamnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_dynamics_model', models.CharField(default='demand_capacity_elastic', max_length=100)),
                ('baseline_capacity_abundance', models.CharField(default='normal', max_length=30)),
                ('fuel_index_baseline_usd_per_barrel', models.DecimalField(decimal_places=2, default='80.00', max_digits=7)),
                ('fuel_index_volatility_sigma', models.DecimalField(decimal_places=3, default='0.120', max_digits=5)),
                ('container_rate_volatility_sigma', models.DecimalField(decimal_places=3, default='0.150', max_digits=5)),
                ('demand_elasticity_coefficient', models.DecimalField(decimal_places=2, default='1.30', max_digits=4)),
                ('capacity_response_lag_rounds', models.IntegerField(default=2)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freight_market', to='core.scenario')),
            ],
            options={
                'db_table': 'sc_freight_market',
            },
        ),
        migrations.CreateModel(
            name='HedgePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=20)),
                ('notional', models.DecimalField(decimal_places=2, max_digits=14)),
                ('locked_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('matured', 'Matured')], default='open', max_length=10)),
                ('mtm_current', models.DecimalField(decimal_places=2, default='0.00', max_digits=14)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maturity_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hedges_maturing', to='core.round')),
                ('opened_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hedges_opened', to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hedge_positions', to='core.team')),
            ],
            options={
                'db_table': 'sc_hedge_position',
            },
        ),
        migrations.CreateModel(
            name='ResilienceParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_source_threshold_pct', models.IntegerField(default=70)),
                ('geographic_concentration_threshold_pct', models.IntegerField(default=60)),
                ('critical_component_buffer_days_recommended', models.IntegerField(default=45)),
                ('bullwhip_coefficient_baseline', models.DecimalField(decimal_places=2, default='1.40', max_digits=4)),
                ('resilience_score_weights', models.JSONField(default=dict)),
                ('disruption_cascade_coefficient', models.DecimalField(decimal_places=2, default='0.30', max_digits=4)),
                ('recovery_rate_with_alternatives_multiplier', models.DecimalField(decimal_places=2, default='0.50', max_digits=4)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resilience_parameters', to='core.scenario')),
            ],
            options={
                'db_table': 'sc_resilience_parameters',
            },
        ),
        migrations.CreateModel(
            name='ShippingLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_id', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=2)),
                ('origin_port', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=2)),
                ('destination_port', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=50)),
                ('modes', models.JSONField(default=dict)),
                ('chokepoints', models.JSONField(default=dict)),
                ('disruption_exposure', models.JSONField(default=dict)),
                ('customs_processing_days_baseline', models.IntegerField()),
                ('reverse_logistics_available', models.BooleanField(default=False)),
                ('reverse_logistics_cost_multiplier', models.DecimalField(decimal_places=2, default='1.00', max_digits=4)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_lanes', to='core.scenario')),
            ],
            options={
                'db_table': 'sc_shipping_lane',
            },
        ),
        migrations.CreateModel(
            name='LogisticsDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_sea_pct', models.IntegerField(default=0)),
                ('mode_air_pct', models.IntegerField(default=0)),
                ('mode_rail_pct', models.IntegerField(default=0)),
                ('mode_road_pct', models.IntegerField(default=0)),
                ('volume_commitment_teu', models.IntegerField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_decisions', to='core.team')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shippinglane')),
            ],
            options={
                'db_table': 'sc_logistics_decision',
            },
        ),
        migrations.CreateModel(
            name='LaneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_disruption', models.JSONField(blank=True, null=True)),
                ('current_rate_modifier', models.DecimalField(decimal_places=3, default='1.000', max_digits=5)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.shippinglane')),
            ],
            options={
                'db_table': 'sc_lane_state',
            },
        ),
        migrations.CreateModel(
            name='SinosureEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_pct', models.IntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marketdefinition')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinosure_enrollments', to='core.team')),
            ],
            options={
                'db_table': 'sc_sinosure_enrollment',
            },
        ),
        migrations.CreateModel(
            name='SourcingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_2_3_visibility_investment', models.CharField(default='none', max_length=20)),
                ('multi_sourcing_strategy', models.CharField(default='single_source', max_length=30)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_decisions', to='core.team')),
            ],
            options={
                'db_table': 'sc_sourcing_decision',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('tier', models.IntegerField()),
                ('capacity_units_per_round', models.IntegerField()),
                ('base_unit_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quality_rating', models.DecimalField(decimal_places=3, max_digits=4)),
                ('reliability_rating', models.DecimalField(decimal_places=3, max_digits=4)),
                ('lead_time_days_baseline', models.IntegerField()),
                ('min_order_commitment', models.IntegerField(default=0)),
                ('specialization', models.JSONField(default=list)),
                ('volume_discount_tiers', models.JSONField(default=list)),
                ('tier_2_3_profile', models.JSONField(default=dict)),
                ('origin_trust_to_buyers', models.JSONField(default=dict)),
                ('certifications', models.JSONField(default=list)),
                ('accepts_trade_finance', models.JSONField(default=list)),
                ('political_risk_profile', models.JSONField(default=dict)),
                ('multi_source_substitutability', models.JSONField(default=list)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.scenario')),
            ],
            options={
                'db_table': 'sc_supplier',
            },
        ),
        migrations.CreateModel(
            name='SourcingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_input_category', models.CharField(max_length=100)),
                ('allocation_pct', models.IntegerField()),
                ('volume_commitment_units', models.IntegerField(default=0)),
                ('payment_terms', models.CharField(max_length=100)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_allocations', to='core.team')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
            ],
            options={
                'db_table': 'sc_sourcing_allocation',
            },
        ),
        migrations.CreateModel(
            name='SupplierState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_multiplier', models.DecimalField(decimal_places=3, default='1.000', max_digits=5)),
                ('quality_modifier', models.DecimalField(decimal_places=3, default='1.000', max_digits=5)),
                ('reliability_modifier', models.DecimalField(decimal_places=3, default='1.000', max_digits=5)),
                ('additional_lead_time_days', models.IntegerField(default=0)),
                ('disruption_cost_multiplier', models.DecimalField(decimal_places=3, default='1.000', max_digits=5)),
                ('recovery_rounds_remaining', models.IntegerField(default=0)),
                ('active_disruption_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventinstance')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.supplier')),
            ],
            options={
                'db_table': 'sc_supplier_state',
            },
        ),
        migrations.CreateModel(
            name='TradeFinanceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_payment_instrument', models.CharField(max_length=100)),
                ('lc_doc_prep_investment', models.CharField(default='standard', max_length=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marketdefinition')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.segmentdefinition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_finance_decisions', to='core.team')),
            ],
            options={
                'db_table': 'sc_trade_finance_decision',
            },
        ),
        migrations.CreateModel(
            name='TradeFinanceInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('cost_bps_of_transaction', models.IntegerField(blank=True, null=True)),
                ('cost_pct_of_insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processing_lead_days', models.IntegerField(default=0)),
                ('seller_protection', models.CharField(max_length=20)),
                ('buyer_cash_requirement', models.CharField(max_length=20)),
                ('available_in_markets', models.JSONField(default=list)),
                ('available_to_home_countries', models.JSONField(default=list)),
                ('rejection_probability_baseline', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('buyer_default_probability_baseline', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('coverage_ceiling_pct', models.IntegerField(blank=True, null=True)),
                ('bri_market_premium_subsidy_pct', models.IntegerField(blank=True, null=True)),
                ('tenor_options_days', models.JSONField(default=list)),
                ('currency_pairs_available', models.JSONField(default=list)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_finance_instruments', to='core.scenario')),
            ],
            options={
                'db_table': 'sc_trade_finance_instrument',
            },
        ),
        migrations.CreateModel(
            name='ComplianceRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('enforcing_market', models.CharField(blank=True, max_length=100, null=True)),
                ('enforcing_country', models.CharField(blank=True, max_length=2, null=True)),
                ('applies_to_products', models.JSONField(default=list)),
                ('trigger_condition', models.CharField(blank=True, max_length=200, null=True)),
                ('trigger_threshold_pct', models.IntegerField(blank=True, null=True)),
                ('baseline_enforcement_probability_per_round', models.DecimalField(decimal_places=4, default='0.0', max_digits=5)),
                ('detention_consequence', models.JSONField(default=dict)),
                ('mitigation_investments', models.JSONField(default=dict)),
                ('phase_in_schedule', models.JSONField(default=list)),
                ('tariff_per_ton_co2_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sectors_covered', models.JSONField(default=list)),
                ('restricted_technologies', models.JSONField(default=list)),
                ('target_countries_baseline', models.JSONField(default=list)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_regimes', to='core.scenario')),
            ],
            options={
                'db_table': 'sc_compliance_regime',
                'unique_together': {('scenario', 'regime_id')},
            },
        ),
        migrations.CreateModel(
            name='ContingencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disruption_response_playbook', models.TextField(blank=True, max_length=500)),
                ('alt_supplier_activation_rules', models.JSONField(default=list)),
                ('mode_switch_triggers', models.JSONField(default=list)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingency_plans', to='core.team')),
            ],
            options={
                'db_table': 'sc_contingency_plan',
                'unique_together': {('team', 'round')},
            },
        ),
        migrations.CreateModel(
            name='CustomsClassificationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('processing_trade', 'Processing Trade'), ('general_trade', 'General Trade'), ('bonded_logistics', 'Bonded Logistics')], default='general_trade', max_length=30)),
                ('reverse_logistics_capacity_pct', models.IntegerField(default=0)),
                ('destination_market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marketdefinition')),
                ('reverse_logistics_hub_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverse_logistics_hub_for', to='core.marketdefinition')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_classification_decisions', to='core.team')),
            ],
            options={
                'db_table': 'sc_customs_classification_decision',
                'unique_together': {('team', 'round', 'destination_market')},
            },
        ),
        migrations.CreateModel(
            name='FXHedgeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=20)),
                ('hedge_ratio', models.IntegerField(default=0)),
                ('tenor_days', models.IntegerField(default=90)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_hedge_decisions', to='core.team')),
            ],
            options={
                'db_table': 'sc_fx_hedge_decision',
                'unique_together': {('team', 'round', 'currency_pair')},
            },
        ),
        migrations.CreateModel(
            name='IncotermsDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoterms', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('CPT', 'CPT'), ('CIP', 'CIP'), ('DAP', 'DAP'), ('DPU', 'DPU'), ('DDP', 'DDP')], default='CIF', max_length=3)),
                ('insurance_coverage_pct', models.IntegerField(default=110)),
                ('destination_market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marketdefinition')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoterms_decisions', to='core.team')),
            ],
            options={
                'db_table': 'sc_incoterms_decision',
                'unique_together': {('team', 'round', 'destination_market')},
            },
        ),
        migrations.CreateModel(
            name='InventoryDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_days', models.IntegerField(default=30)),
                ('safety_stock_trigger_pct', models.IntegerField(default=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marketdefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teamproduct')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_decisions', to='core.team')),
            ],
            options={
                'db_table': 'sc_inventory_decision',
                'unique_together': {('team', 'round', 'product', 'market')},
            },
        ),
        migrations.CreateModel(
            name='ResilienceScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('components', models.JSONField(default=dict)),
                ('weights_used', models.JSONField(default=dict)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resilience_history', to='core.team')),
            ],
            options={
                'db_table': 'sc_resilience_score_history',
                'unique_together': {('team', 'round')},
            },
        ),
        migrations.CreateModel(
            name='SCEventInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affects_all_teams', models.BooleanField(default=True)),
                ('fired_by_instructor', models.BooleanField(default=False)),
                ('resolution_data', models.JSONField(default=dict)),
                ('affected_teams', models.ManyToManyField(blank=True, to='core.team')),
                ('event_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.eventtemplatedefinition')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
            ],
            options={
                'db_table': 'sc_event_instance',
                'indexes': [models.Index(fields=['round'], name='sc_event_in_round_i_ad3097_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shippinglane',
            index=models.Index(fields=['scenario', 'origin_country', 'destination_country'], name='sc_shipping_scenari_94ff3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippinglane',
            unique_together={('scenario', 'lane_id')},
        ),
        migrations.AlterUniqueTogether(
            name='logisticsdecision',
            unique_together={('team', 'round', 'lane')},
        ),
        migrations.AlterUniqueTogether(
            name='lanestate',
            unique_together={('round', 'lane')},
        ),
        migrations.AlterUniqueTogether(
            name='sinosureenrollment',
            unique_together={('team', 'round', 'market')},
        ),
        migrations.AlterUniqueTogether(
            name='sourcingdecision',
            unique_together={('team', 'round')},
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['scenario', 'country'], name='sc_supplier_scenari_323fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['scenario', 'tier'], name='sc_supplier_scenari_488154_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('scenario', 'supplier_id')},
        ),
        migrations.AddIndex(
            model_name='sourcingallocation',
            index=models.Index(fields=['team', 'round'], name='sc_sourcing_team_id_2179c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcingallocation',
            unique_together={('team', 'round', 'critical_input_category', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierstate',
            unique_together={('round', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='tradefinancedecision',
            unique_together={('team', 'round', 'segment', 'market')},
        ),
        migrations.AlterUniqueTogether(
            name='tradefinanceinstrument',
            unique_together={('scenario', 'instrument_id')},
        ),
    ]
