# Generated by Django 5.2.4 on 2026-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_sc_scenario_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionesg',
            name='cbam_reporting_readiness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decisionesg',
            name='scope_3_emissions_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decisionesg',
            name='scope_3_investment_usd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionesg',
            name='supplier_audit_program',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('comprehensive', 'Comprehensive')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='decisionesg',
            name='uflpa_tier_mapping_investment',
            field=models.CharField(choices=[('none', 'None'), ('partial', 'Partial'), ('full', 'Full')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='decisionplant',
            name='reverse_logistics_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decisionplant',
            name='scope_1_co2_per_unit_kg',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=7),
        ),
        migrations.AddField(
            model_name='decisionplant',
            name='scope_2_co2_per_unit_kg',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=7),
        ),
        migrations.AddField(
            model_name='decisionplant',
            name='sourcing_node_role',
            field=models.CharField(choices=[('owned_manufacturing', 'Owned Manufacturing'), ('contract_manufacturing', 'Contract Manufacturing'), ('pure_assembly', 'Pure Assembly')], default='owned_manufacturing', max_length=30),
        ),
        migrations.AddField(
            model_name='decisionplant',
            name='upstream_suppliers_required',
            field=models.JSONField(default=list),
        ),
    ]
