# Generated by Django 5.2.4 on 2026-04-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_decision_plant_sc_extensions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAction',
        ),
        migrations.DeleteModel(
            name='ComponentStatus',
        ),
        migrations.DeleteModel(
            name='CumulativeSales',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
