# Generated by Django 5.2.4 on 2026-04-19 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_cc05_promote_group_f_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProgressiveDisclosureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(help_text="Dot-notation field path, e.g. 'sourcing.payment_terms'.", max_length=200)),
                ('override_unlock_round', models.IntegerField(help_text='Round at which the field unlocks for this class.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_disclosure_overrides', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(help_text='The Game (class instance) this override applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_overrides', to='core.game')),
            ],
            options={
                'db_table': 'class_progressive_disclosure_override',
                'indexes': [models.Index(fields=['game'], name='class_progr_game_id_a05c53_idx')],
                'unique_together': {('game', 'field_path')},
            },
        ),
        migrations.CreateModel(
            name='ClassResilienceWeightOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_name', models.CharField(choices=[('multi_sourcing', 'Multi-sourcing'), ('geographic_diversity', 'Geographic Diversity'), ('buffer_inventory_adequacy', 'Buffer Inventory Adequacy'), ('modal_flexibility', 'Modal Flexibility'), ('tier_2_visibility', 'Tier-2 Visibility'), ('supplier_financial_health', 'Supplier Financial Health')], max_length=50)),
                ('override_value', models.DecimalField(decimal_places=3, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_weight_overrides', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resilience_weight_overrides', to='core.game')),
            ],
            options={
                'db_table': 'class_resilience_weight_override',
                'unique_together': {('game', 'weight_name')},
            },
        ),
    ]
