# Generated by Django 5.2.4 on 2026-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_instructor_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplatedefinition',
            name='sc_effects',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
