# Generated by Django 5.2.4 on 2026-07-13 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_cc19b_resilience_disruption_impact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEnforcementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_usd', models.DecimalField(decimal_places=2, default='0.00', max_digits=14)),
                ('freeze_until_round', models.IntegerField(default=0)),
                ('reputation_impact', models.DecimalField(decimal_places=3, default='0.000', max_digits=6)),
                ('triggered_by', models.CharField(blank=True, max_length=200)),
                ('mitigated', models.BooleanField(default=False)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.marketdefinition')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enforcement_events', to='core.complianceregime')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='core.team')),
            ],
            options={
                'db_table': 'sc_compliance_enforcement_event',
                'indexes': [models.Index(fields=['team', 'round'], name='sc_complian_team_id_2614f9_idx')],
            },
        ),
    ]
