# Generated by Django 5.2.4 on 2026-07-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_complianceenforcementevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceenforcementevent',
            name='narrative',
            field=models.TextField(blank=True, default=''),
        ),
    ]
