# Generated by Django 5.2.4 on 2026-07-15 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_complianceenforcementevent_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('deadline', 'Deadline elapsed'), ('manual', 'Closed by instructor')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='round',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('game_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, default='', max_length=200)),
                ('login_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'db_table': 'user_session',
                'indexes': [models.Index(fields=['game_id', 'last_seen_at'], name='user_sessio_game_id_a32d6f_idx')],
            },
        ),
    ]
