# Generated by Django 5.2.4 on 2026-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_round_close_reason_round_closed_at_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplatform',
            name='accumulated_amortization',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amortization charged against capitalized_cost to date.', max_digits=15),
        ),
        migrations.AddField(
            model_name='teamplatform',
            name='capitalized_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform development cost carried as an asset rather than expensed at commit time. Only populated when the scenario sets capitalize_platform_development.', max_digits=15),
        ),
    ]
