# Generated by Django 5.2.4 on 2026-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_teamplatform_accumulated_amortization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresultfinancials',
            name='platform_amortization',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Straight-line amortization of capitalized platform development cost.', max_digits=15),
        ),
    ]
