# Generated by Django 5.2.4 on 2026-08-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_team_participation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutionmanifest',
            name='decision_event_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='environment',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='input_body_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='input_section_digests',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='narrative_manifest',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='narrative_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='output_body_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='output_section_digests',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resolutionmanifest',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
