# Generated by Django 5.2.4 on 2026-08-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_resolutionmanifest_decision_event_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutionmanifest',
            name='source_tree_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
