# Generated by Django 5.2.4 on 2026-08-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_resolutionmanifest_source_tree_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorauditevent',
            name='conflict',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='operatorauditevent',
            name='outcome',
            field=models.CharField(choices=[('committed', 'Committed'), ('rejected', 'Rejected')], default='committed', max_length=16),
        ),
    ]
