# Generated by Django 5.2.4 on 2026-08-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_operatorauditevent_conflict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_type', models.CharField(choices=[('briefing', 'Strategic briefings'), ('coherence_rag', 'Coherence RAG evaluation'), ('coaching', 'Instructor coaching alerts'), ('outlook', 'Market outlooks'), ('sc_event', 'Supply-chain event narratives'), ('compliance', 'Compliance enforcement narratives')], max_length=32)),
                ('template_version', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed by a worker'), ('succeeded', 'Succeeded'), ('failed', 'Failed — terminal, needs an operator retry')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('claimed_by', models.CharField(blank=True, default='', max_length=128)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('model_endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narrative_jobs', to='core.game')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narrative_jobs', to='core.round')),
            ],
            options={
                'db_table': 'narrative_job',
                'ordering': ['round_id', 'narrative_type'],
                'indexes': [models.Index(fields=['state', 'claim_expires_at'], name='narrative_job_claimable')],
                'unique_together': {('round', 'narrative_type', 'template_version')},
            },
        ),
    ]
