# Generated by Django 5.2.4 on 2026-08-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_narrativejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceventinstance',
            name='narrative',
            field=models.TextField(blank=True, default=''),
        ),
    ]
