# Generated by Django 5.2.4 on 2026-08-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_sceventinstance_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoralert',
            name='source',
            field=models.CharField(choices=[('engine', 'Deterministic engine'), ('narrative', 'Phase-2 narrative')], default='engine', max_length=16),
        ),
    ]
