# Generated by Django 5.2.4 on 2026-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_instructoralert_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativejob',
            name='degraded',
            field=models.BooleanField(default=False),
        ),
    ]
