# Generated by Django 5.2.4 on 2026-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_move_sc_event_narrative'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.BigIntegerField(unique=True)),
                ('source_table', models.CharField(max_length=64)),
                ('source_id', models.BigIntegerField()),
                ('row_sha256', models.CharField(max_length=64)),
                ('prev_sha256', models.CharField(max_length=64)),
                ('entry_sha256', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competition_audit_chain',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['source_table', 'source_id'], name='competition_source__2c4821_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_table', 'recovery_audit_file'), _negated=True), fields=('source_table', 'source_id'), name='audit_chain_one_entry_per_row')],
            },
        ),
        migrations.CreateModel(
            name='SensitiveReadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('game_id_read', models.IntegerField(blank=True, null=True)),
                ('team_id_read', models.IntegerField(blank=True, null=True)),
                ('round_number_read', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('decisions', 'Raw team decisions'), ('audit', 'Audit payload')], max_length=16)),
                ('route', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied'), ('error', 'Error')], max_length=8)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competition_sensitive_read_event',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['game_id_read', 'team_id_read', 'round_number_read'], name='competition_game_id_eeb920_idx'), models.Index(fields=['actor_user_id', 'created_at'], name='competition_actor_u_1fe938_idx'), models.Index(fields=['created_at'], name='competition_created_12b83e_idx')],
            },
        ),
    ]
