# Generated by Django 5.2.4 on 2026-08-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_reference_prices_by_positioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationRefusalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('game_id_attempted', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(max_length=8)),
                ('route', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('outcome', models.CharField(default='rejected', max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competition_authorization_refusal_event',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['game_id_attempted', 'created_at'], name='competition_game_id_45c654_idx'), models.Index(fields=['actor_user_id', 'created_at'], name='competition_actor_u_e8204d_idx'), models.Index(fields=['created_at'], name='competition_created_480037_idx')],
            },
        ),
    ]
