# Generated by Django 5.2.4 on 2026-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_authorization_refusal_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplatform',
            name='funded_round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamplatform',
            name='status',
            field=models.CharField(choices=[('unfunded_draft', 'Unfunded Draft'), ('active', 'Active'), ('in_development', 'In Development'), ('retired', 'Retired')], max_length=20),
        ),
    ]
