# Generated by Django 5.2.4 on 2026-09-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_platform_funding_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProductPlatformHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('effective_from_round', models.IntegerField()),
                ('switched_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_written_off_units', models.IntegerField(default=0)),
                ('inventory_write_off', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('team_platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_history', to='core.teamplatform')),
                ('team_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_history', to='core.teamproduct')),
            ],
            options={
                'db_table': 'team_product_platform_history',
                'ordering': ['team_product_id', 'effective_from_round', 'id'],
                'indexes': [models.Index(fields=['team_product', 'effective_from_round'], name='team_produc_team_pr_7f54d6_idx')],
                'unique_together': {('team_product', 'effective_from_round')},
            },
        ),
    ]
