# Generated by Django 5.2.4 on 2026-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_product_platform_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresultfinancials',
            name='platform_switch_write_off',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock left unsellable by re-basing a product onto another platform, written off at the authored percentage.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='teamproductplatformhistory',
            name='inventory_written_off_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
