# Generated by Django 5.2.4 on 2026-09-04 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_stage4_write_off_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResultAIAdoption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('fit_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('attractiveness', models.DecimalField(decimal_places=4, max_digits=10)),
                ('share_pct', models.DecimalField(decimal_places=6, max_digits=7)),
                ('new_adopters', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ai_competitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_results', to='core.aicompetitordefinition')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_adoption_results', to='core.game')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_adoption_results', to='core.marketdefinition')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_adoption_results', to='core.segmentdefinition')),
            ],
            options={
                'db_table': 'round_result_ai_adoption',
                'unique_together': {('game', 'round_number', 'ai_competitor', 'segment', 'market')},
            },
        ),
        migrations.CreateModel(
            name='RoundResultDemandReconciliation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('adoption_pool', models.DecimalField(decimal_places=2, max_digits=15)),
                ('human_adopters', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ai_adopters', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unserved_adopters', models.DecimalField(decimal_places=2, max_digits=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_reconciliations', to='core.game')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_reconciliations', to='core.marketdefinition')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_reconciliations', to='core.segmentdefinition')),
            ],
            options={
                'db_table': 'round_result_demand_reconciliation',
                'unique_together': {('game', 'round_number', 'segment', 'market')},
            },
        ),
    ]
