# Generated by Django 4.2 on 2026-09-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_calibration_demand_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResultProductDemand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('fit_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('adjusted_fit_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('market_readiness_pct', models.DecimalField(decimal_places=4, max_digits=5)),
                ('attractiveness', models.DecimalField(decimal_places=4, max_digits=10)),
                ('share_pct', models.DecimalField(decimal_places=6, max_digits=7)),
                ('unconstrained_demand', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_production', models.DecimalField(decimal_places=2, max_digits=15)),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lost_demand', models.DecimalField(decimal_places=2, max_digits=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                            related_name='product_demand_results', to='core.game')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name='product_demand_results', to='core.marketdefinition')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               related_name='product_demand_results', to='core.segmentdefinition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                            related_name='product_demand_results', to='core.team')),
                ('team_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='demand_results', to='core.teamproduct')),
            ],
            options={
                'db_table': 'round_result_product_demand',
                'unique_together': {('game', 'round_number', 'team', 'team_product', 'segment', 'market')},
            },
        ),
    ]
