# Generated by Django 5.2.4 on 2026-09-12 03:33
#
# Downgrade guard added 2026-09-21 (V2-041 rollback hazard, launch checklist).
# The forward operation, the dependencies and the name are unchanged: this
# migration is already applied in production, so only its REVERSE path may
# differ. `RunPython(noop, guard)` does nothing forwards and has no effect on
# the model state, so an already-migrated database sees no difference and
# `makemigrations --check` stays clean.

from django.db import migrations, models


class NullPricesBlockDowngrade(Exception):
    """Reversing 0085 would have to invent or destroy a team's decision."""


def refuse_downgrade_while_null_prices_exist(apps, schema_editor):
    """Refuse to reverse while any `decision_marketing.retail_price` is null.

    Since the not-for-sale rule (owner rulings R15/R24), a null price is a
    legitimate stored decision: "this product was not offered for sale in this
    market this round". It can sit inside a RESOLVED round, where
    `decision_marketing` is a hashed section of the competitive manifest.

    Reversing the `AlterField` restores NOT NULL. With null rows present
    PostgreSQL refuses that on its own, but with a bare `NotNullViolation` that
    names neither the rows nor what to do. Making the reversal "safe" instead
    -- filling a price or deleting the rows here -- would silently rewrite a
    decision a team really made, and for a resolved round would change hashed
    evidence. So this names the rows and stops. Nothing is modified.
    """
    DecisionMarketing = apps.get_model('core', 'DecisionMarketing')
    rows = (DecisionMarketing.objects
            .filter(retail_price__isnull=True)
            .order_by('pk'))
    total = rows.count()
    if not total:
        return

    sample = []
    for row in rows.select_related('submission__round__game',
                                   'submission__team')[:10]:
        submission = row.submission
        round_obj = submission.round
        sample.append(
            f'decision_marketing #{row.pk} (game {round_obj.game_id}, '
            f'round {round_obj.round_number} [{round_obj.status}], '
            f'team "{submission.team.name}")')
    more = f' ... and {total - len(sample)} more' if total > len(sample) else ''

    raise NullPricesBlockDowngrade(
        f'REFUSED: cannot reverse core.0085_price_band_blank_price. '
        f'{total} decision_marketing row(s) hold a null retail_price, which '
        f'is a legitimate "not offered for sale" decision (R15/R24) and may '
        f'belong to a resolved round. Reversing restores NOT NULL and cannot '
        f'represent them. Nothing was changed by this migration. '
        f'Rows: {"; ".join(sample)}{more}. '
        f'Before retrying: take a competition backup, then price or delete '
        f'every such row deliberately -- and know that doing so to a '
        f'processed round changes its hashed decision_marketing section, so '
        f'that round will no longer replay to its recorded manifest. '
        f'NOTE: migrations unapplied before this one in the same command '
        f'(the empty merge 0087, and 0086 if it was reached first) stay '
        f'unapplied; run `manage.py migrate core` to return to head.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_product_level_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionmarketing',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        # Reverse-only guard. Operations are reversed last-to-first, so placing
        # it AFTER the AlterField makes it run BEFORE the NOT NULL is restored.
        migrations.RunPython(
            migrations.RunPython.noop,
            refuse_downgrade_while_null_prices_exist,
        ),
    ]
