# Generated by Django 5.2.4 on 2026-09-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_product_level_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionmarketing',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
