# Generated by Django 5.2.4 on 2026-09-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_price_band_blank_price'),
        ('core', '0086_paid_research_reports'),
    ]

    operations = [
    ]
