"""R47: compliance investment gets its own line on the income statement.

Adds `compliance_expense` to `round_result_financials`, default 0. Rounds
resolved before this migration carry no compliance investment (V2-137: no
team could save one), so the default is the true historical value and no
row is backfilled. No existing table or migration is altered. The column is
a hashed field of the `financials` manifest section, which is why the
manifest schema version moves to 7 in the same change.

Reverse drops the column.
"""
# Generated by Django 5.2.4 on 2026-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_game_deletion_audit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresultfinancials',
            name='compliance_expense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='R47: compliance investment the team made this round, charged from cash at resolution; its own line on the income statement by owner ruling.', max_digits=15),
        ),
    ]
